name: 'preview-app'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
jobs:
  hasura-cloud-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hasura/hasura-cloud-preview-apps@v0.1.9
        with:
          name: "preview-lend-a-book-${{github.env.GITHUB_HEAD_REF}}${{github.event.number}}"
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.POSTGRES_SERVER_CONNECTION_URI}}
#            PG_ENV_VARS_FOR_HASURA=
          hasuraProjectDirectoryPath: /backend/hasura
          region: us-west-1
          tier: cloud_free
          hasuraEnv: |
            NOTHING=YET
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
      - uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          id: preview_app_comment
          number: ${{github.event.number}}
          repository: ${{env.GITHUB_REPOSITORY}}
          message: |
            Console URL available at ${{steps.hasura_cloud_preview.outputs.consoleURL}}
            GraphQL Endpoint available at ${{steps.hasura_cloud_preview.outputs.graphQLEndpoint}}